name: main

on: [push]

jobs:
  main-win:
    name: Test on Windows
    runs-on: windows-latest

    steps:
      - name: Check out files
        uses: actions/checkout@main

      - name: Setup gsc-tool
        uses: xensik/setup-gsc-tool@v1
        with:
          version: '1.4.0'

      - name: Compile test script
        run: |
          gsc-tool.exe -m parse -g iw5 -s pc .
